language: ruby

rvm:
  - 2.2.4
  - 2.3.0

gemfile:
  - test/gemfiles/Gemfile.rails-3.2.x
  - test/gemfiles/Gemfile.rails-4.0.x
  - test/gemfiles/Gemfile.rails-4.1.x
  - test/gemfiles/Gemfile.rails-4.2.x
  - test/gemfiles/Gemfile.rails-5.0.x

matrix:
  exclude:
    - rvm: 2.3.0
      gemfile: test/gemfiles/Gemfile.rails-3.2.x